### ISSUE TITLE
key generation

### ISSUE THREAD

**Issue by kavish-s** [8rupees/captcha_2727#8]
The new keys are generated in the same dir as the source and deleting the keys in the Keys dir messes up bug.py
![Screenshot 2024-09-05 202428](https://github.com/user-attachments/assets/7eb505d0-6643-4f58-a6a0-434a2564291b)
everything works well if you don't touch the keys in the Keys dir.

**Comment by 8rupees** [comment]
I have made the necessary changes. Sync with the remote repo. Use this flow:
```
git fetch origin
git reset --hard origin/master
git clean -fd
git pull origin master
```
